#!/bin/sh
set -eu

if [ ! -f "${SEARXNG_SETTINGS_PATH}" ]; then
    mkdir -p "$(dirname "${SEARXNG_SETTINGS_PATH}")"
    cp -f /usr/local/searxng/container/dev-settings.yml "${SEARXNG_SETTINGS_PATH}"
fi

export SEARXNG_DEBUG="${SEARXNG_DEBUG:-1}"
export GRANIAN_PROCESS_NAME="${GRANIAN_PROCESS_NAME:-searxng}"
export GRANIAN_INTERFACE="${GRANIAN_INTERFACE:-wsgi}"
export GRANIAN_HOST="${GRANIAN_HOST:-::}"
export GRANIAN_PORT="${GRANIAN_PORT:-8889}"
export GRANIAN_WEBSOCKETS="${GRANIAN_WEBSOCKETS:-false}"
export GRANIAN_BLOCKING_THREADS="${GRANIAN_BLOCKING_THREADS:-4}"
export GRANIAN_WORKERS_KILL_TIMEOUT="${GRANIAN_WORKERS_KILL_TIMEOUT:-30s}"
export GRANIAN_BLOCKING_THREADS_IDLE_TIMEOUT="${GRANIAN_BLOCKING_THREADS_IDLE_TIMEOUT:-5m}"
export GRANIAN_RELOAD="${GRANIAN_RELOAD:-true}"
export GRANIAN_RELOAD_IGNORE_WORKER_FAILURE="${GRANIAN_RELOAD_IGNORE_WORKER_FAILURE:-true}"
export GRANIAN_RELOAD_PATHS="${GRANIAN_RELOAD_PATHS:-./searx}"

echo "SearXNG dev (Debian) listening on ${GRANIAN_HOST}:${GRANIAN_PORT}"
exec granian searx.webapp:app
